/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supermarket;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author kraji
 */
public class Category extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Category() {
        initComponents();
        selectcategory();
    }
    
public  void selectcategory(){
    
      
        try{
         conn=  (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/SupermarketDB","user1","root");
         stmt= conn.createStatement();
         rs= stmt.executeQuery("select * from user1.CAT");
         Cateogory_Table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            e.printStackTrace();
        }
}
    
    Connection conn;
    Statement stmt;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CatID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CatName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CatDec = new javax.swing.JTextField();
        Clear_Button = new javax.swing.JButton();
        Edit_button = new javax.swing.JButton();
        Del_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cateogory_Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Add_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Russo One", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Manage Category");

        CatID.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CatID.setForeground(new java.awt.Color(102, 102, 255));
        CatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Russo One", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Category ID");

        jLabel4.setFont(new java.awt.Font("Russo One", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Name");

        CatName.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CatName.setForeground(new java.awt.Color(102, 102, 255));
        CatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Russo One", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Description");

        CatDec.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CatDec.setForeground(new java.awt.Color(102, 102, 255));
        CatDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatDecActionPerformed(evt);
            }
        });

        Clear_Button.setBackground(new java.awt.Color(102, 51, 255));
        Clear_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear_Button.setForeground(new java.awt.Color(255, 255, 255));
        Clear_Button.setText("Clear");
        Clear_Button.setBorder(null);
        Clear_Button.setBorderPainted(false);
        Clear_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear_ButtonMouseClicked(evt);
            }
        });
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        Edit_button.setBackground(new java.awt.Color(102, 51, 255));
        Edit_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Edit_button.setForeground(new java.awt.Color(255, 255, 255));
        Edit_button.setText("Edit");
        Edit_button.setToolTipText("");
        Edit_button.setBorder(null);
        Edit_button.setBorderPainted(false);
        Edit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit_buttonMouseClicked(evt);
            }
        });
        Edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_buttonActionPerformed(evt);
            }
        });

        Del_button.setBackground(new java.awt.Color(102, 51, 255));
        Del_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Del_button.setForeground(new java.awt.Color(255, 255, 255));
        Del_button.setText("Delete");
        Del_button.setBorder(null);
        Del_button.setBorderPainted(false);
        Del_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Del_buttonMouseClicked(evt);
            }
        });
        Del_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del_buttonActionPerformed(evt);
            }
        });

        Cateogory_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Description"
            }
        ));
        Cateogory_Table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Cateogory_Table.setRowHeight(25);
        Cateogory_Table.setSelectionBackground(new java.awt.Color(102, 102, 255));
        Cateogory_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cateogory_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Cateogory_Table);

        jLabel2.setFont(new java.awt.Font("Russo One", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Categories List");

        Add_button.setBackground(new java.awt.Color(102, 51, 255));
        Add_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Add_button.setForeground(new java.awt.Color(255, 255, 255));
        Add_button.setText("Add");
        Add_button.setBorder(null);
        Add_button.setBorderPainted(false);
        Add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_buttonMouseClicked(evt);
            }
        });
        Add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addComponent(CatDec, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(CatID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(253, 253, 253)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(CatName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(158, 158, 158))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(241, 241, 241)
                            .addComponent(Add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(Edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(Del_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 286, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CatID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CatName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CatDec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Del_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Russo One", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatIDActionPerformed

    private void CatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatNameActionPerformed

    private void CatDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatDecActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_CatDecActionPerformed

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Clear_ButtonActionPerformed

    private void Edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_buttonActionPerformed

    private void Del_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Del_buttonActionPerformed

    private void Add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_buttonActionPerformed

    private void Add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_buttonMouseClicked
        // TODO add your handling code here:
        
    if(CatID.getText().isEmpty() || CatName.getText().isEmpty() || CatDec.getText().isEmpty()  )  {
        JOptionPane.showMessageDialog(this,"Please fill the Fields");
    }  
    else{
        try{
    
        conn=  (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/SupermarketDB","user1","root");
        
       PreparedStatement add= conn.prepareStatement("insert into CAT values(?,?,?)");
       add.setInt(1,Integer.valueOf(CatID.getText()));
        add.setString(2,CatName.getText());
        add.setString(3,CatDec.getText());
      
         int row=add.executeUpdate();
         JOptionPane.showMessageDialog(this, "Cateogory added succesfully");
         conn.close();
        selectcategory();
    }
    catch(Exception e){
e.printStackTrace();
    }// 
    } 
    }//GEN-LAST:event_Add_buttonMouseClicked

    private void Clear_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear_ButtonMouseClicked
        // TODO add your handling code here:
        CatID.setText("");
        CatName.setText("");
        CatDec.setText("");
        
    }//GEN-LAST:event_Clear_ButtonMouseClicked

    private void Del_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_buttonMouseClicked
        // TODO add your handling code here:
          if(CatID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter Category Id to Delete");
        }
        else{
            try{
                conn=  (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/SupermarketDB","user1","root");
                String Catid=CatID.getText().toString();
                String query="Delete from user1.CAT where CATID ="+Catid;
                Statement add=conn.createStatement();
                add.executeUpdate(query);
                  selectcategory();
                 JOptionPane.showMessageDialog(this, "Category Deleted Succesfully");
            }
            catch(Exception e){
        }
        }
    }//GEN-LAST:event_Del_buttonMouseClicked

    private void Edit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit_buttonMouseClicked
        // TODO add your handling code here:
           
    if(CatID.getText().isEmpty() || CatName.getText().isEmpty() || CatDec.getText().isEmpty())  {
        JOptionPane.showMessageDialog(this,"Missing Field values!!");
    } 
    else {
    try{
        conn=  (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/SupermarketDB","user1","root");
        String query ="Update user1.CAT set CATNAME='"+CatName.getText().toString()+"'"+",CATDEC='"+CatDec.getText().toString()+"'"+" Where CATID="+CatID.getText();
        Statement add=conn.createStatement();
        add.executeUpdate(query);
           JOptionPane.showMessageDialog(this,"Entry Updated succesfully");
             selectcategory();
           
        
    }catch(SQLException e){
        e.printStackTrace();
    }
    }
    }//GEN-LAST:event_Edit_buttonMouseClicked

    private void Cateogory_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cateogory_TableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel) Cateogory_Table.getModel();
        int myindex=Cateogory_Table.getSelectedRow();
        CatID.setText(model.getValueAt(myindex, 0).toString());
         CatName.setText(model.getValueAt(myindex, 1).toString());
         CatDec.setText(model.getValueAt(myindex, 2).toString());
           selectcategory();
    }//GEN-LAST:event_Cateogory_TableMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_button;
    private javax.swing.JTextField CatDec;
    private javax.swing.JTextField CatID;
    private javax.swing.JTextField CatName;
    private javax.swing.JTable Cateogory_Table;
    private javax.swing.JButton Clear_Button;
    private javax.swing.JButton Del_button;
    private javax.swing.JButton Edit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
